const initialState = {
    searchResults: [],
    // bodyPartList: [
    //     'back',
    //     'cardio',
    //     'chest',
    //     'lower arms',
    //     'lower legs',
    //     'neck',
    //     'shoulders',
    //     'upper arms',
    //     'upper legs',
    //     'waist',
    // ],
    bodyPartList: [{name: "back",
image: "http://backpicture.com"},
{name: "cardio",
image: ""},
{name: "chest",
image: ""},
{name: "lower arms",
image: ""},
{name: "lower legs",
image: ""},
{name: "neck",
image: ""},
{name: "shoulders",
image: ""},
{name: "upper arms",
image: ""},
{name: "upper legs",
image: ""},
{name: "waist",
image: ""}
],
    targetMuscleList: [
        'abductors',
        'abs',
        'adductors',
        'biceps',
        'calves',
        'cardiovascular system',
        'delts',
        'forearms',
        'glutes',
        'hamstrings',
        'lats',
        'levator scapulae',
        'pectorals',
        'quads',
        'serratus anterior',
        'spine',
        'traps',
        'triceps',
        'upper back',
    ],
    equipmentList: [
        'assisted',
        'band',
        'barbell',
        'body weight',
        'bosu ball',
        'cable',
        'dumbbell',
        'elliptical machine',
        'ez barbell',
        'hammer',
        'kettlebell',
        'leverage machine',
        'medicine ball',
        'olympic barbell',
        'resistance band',
        'roller',
        'rope',
        'skierg machine',
        'sled machine',
        'smith machine',
        'stability ball',
        'stationary bike',
        'stepmill machine',
        'tire',
        'trap bar',
        'upper body ergometer',
        'weighted',
        'wheel roller',
    ],
    
}

export default initialState
